name: Tests

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest, windows-latest, macos-latest]
      #fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} (Miniconda)
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
    - name: Install build dependencies
      shell: bash -l {0}
      run: |
        conda install -n base numpy
        conda install numpy cython cxx-compiler
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      if: ${{ runner.os == 'Windows' }}
    - name: Build
      shell: bash -l {0}
      run: |
        python setup.py build_ext --inplace
        python setup.py develop
    - name: Import module
      shell: bash -l {0}
      run: python -c "import fa2"
